export enum Path {
  APIGraphql = '/api/graphql',
  LP = '/',
  Auth = '/auth',
  Problem = '/problem',
  ProblemCreate = '/problem/create',
  ProblemEdit = '/problem/edit',
  ProblemAnswer = '/problem/answer',
  ProblemAnswerRedeem = '/problem/answer/redeem',
  ProblemAnswerReview = '/problem/answer/review',
  ProfileSettings = '/settings/profile',
  NotificationSettings = '/settings/notifications',
  PaymentSettings = '/settings/payment',
  Tip = '/tip',
  PaymentSubscription = '/payment/subscription',
  Descriptors = '/descriptors/task2',
}
