export enum Path {
  APIGraphql = '/query',
  Problem = '/',
  ProblemCreate = '/problem/create',
  ProblemEdit = '/problem/edit/:problemId',
  ProblemDetail = '/problem/:problemId',
  ProblemAnswer = '/problem/answer/:problemId',
  ProblemAnswerRedeem = '/problem/answer/redeem/:answerId',
  ProblemAnswerReview = '/problem/answer/review/:answerId',
  ProfileSettings = '/settings/profile',
  NotificationSettings = '/settings/notifications',
  PaymentSettings = '/settings/payment',
  Tip = '/tip',
  PaymentSubscription = '/payment/subscription',
  Descriptors = '/descriptors/task2',
  Terms = 'https://www.ielts-writing-helper.com/terms',
}
